#for reference so we dont have to keep writing it everywhere, we can just call it DRY
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo_user: bW9uZ291c2Vy #base64 mongouser
  mongo_password:  bW9uZ29wYXNzd29yZA== #base64 mongopassword