apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret #secret metdata name
              key: mongo_user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret #secret metdata name
              key: mongo_password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-config #file name,mongo-config.yaml, its not a scret so its stored in config
              key: mongo_url #config data

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp # attach service to deployment called mongo in deplyment selectormatchlabel
  ports:
    - protocol: TCP
      port: 8081 #can be any port
      targetPort: 8081  #deployment container port
      nodePort: 30100 #nodeport work with specific range 30000-32767 not just any port 